<?php

use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->insert([
            ['name' => 'أبخازيا', 'name_tr' => 'Abhazya','code'=>'+7 840'],
            ['name' => 'أبخازيا', 'name_tr' => 'Abhazya','code'=>'+7 940'],
            ['name' => 'أبخازيا', 'name_tr' => 'Abhazya','code'=>'+995 44'],
            ['name' => 'أفغانستان', 'name_tr' => 'Afganistan','code'=>'+93'],
            ['name' => 'جزر آلاند', 'name_tr' => 'Aland Adaları','code'=>'+358 18'],
            ['name' => 'ألبانيا', 'name_tr' => 'Arnavutluk','code'=>'+355'],
            ['name' => 'الجزائر', 'name_tr' => 'Cezayir','code'=>'+213'],
            ['name' => 'ساموا الأمريكية', 'name_tr' => 'Amerikan Samoası','code'=>'+1 684'],
            ['name' => 'أندورا', 'name_tr' => 'Andorra','code'=>'+376'],
            ['name' => 'أنغولا', 'name_tr' => 'Angora','code'=>'+244'],
            ['name' => 'أنغيلا', 'name_tr' => 'Anguilla','code'=>'+1 264'],
            ['name' => 'أنتيغوا باربودا', 'name_tr' => 'Antigua Barbuda','code'=>'+1 268'],
            ['name' => 'الأرجنتين', 'name_tr' => 'Arjantin','code'=>'+54'],
            ['name' => 'أرمينيا', 'name_tr' => 'Ermenistan','code'=>'+374'],
            ['name' => 'أروبا', 'name_tr' => 'Aruba','code'=>'+297'],
            ['name' => 'صعود', 'name_tr' => 'Yükselişi','code'=>'+247'],
            ['name' => 'أستراليا', 'name_tr' => 'Avustralya','code'=>'+61'],
            ['name' => 'الأقاليم الخارجية الأسترالية', 'name_tr' => 'Avustralya denizaşırı bölgeleri','code'=>'+672'],
            ['name' => 'النمسا', 'name_tr' => 'Avusturya','code'=>'+43'],
            ['name' => 'أذربيجان', 'name_tr' => 'Azerbeycan','code'=>'+994'],
            ['name' => 'الباهاما', 'name_tr' => 'Bahamalar','code'=>'+1 242'],
            ['name' => 'البحرين', 'name_tr' => 'Bahreyn','code'=>'+973'],
            ['name' => 'بنغلاديش', 'name_tr' => 'Bangladeş','code'=>'+880'],
            ['name' => 'بربادوس', 'name_tr' => 'Barbados','code'=>'+1 246'],
            ['name' => 'باربودا', 'name_tr' => 'Barbuda','code'=>'+1 268'],
            ['name' => 'روسيا البيضاء', 'name_tr' => 'Beyaz rusya','code'=>'+375'],
            ['name' => 'بلجيكا', 'name_tr' => 'Belçika','code'=>'+32'],
            ['name' => 'بليز', 'name_tr' => 'Belize','code'=>'+501'],
            ['name' => 'بنين', 'name_tr' => 'Benin','code'=>'+229'],
            ['name' => 'برمودا', 'name_tr' => 'Bermuda','code'=>'+1 441'],
            ['name' => 'بوتان', 'name_tr' => 'Butan','code'=>'+975'],
            ['name' => 'بوليفيا', 'name_tr' => 'Bolivya','code'=>'+591'],
            ['name' => 'البوسنة والهرسك', 'name_tr' => 'Bosna Hersek','code'=>'+387'],
            ['name' => 'بوتسوانا', 'name_tr' => 'Botsvana','code'=>'+267'],
            ['name' => 'البرازيل', 'name_tr' => 'Brezilya','code'=>'+55'],
            ['name' => 'إقليم المحيط البريطاني الهندي', 'name_tr' => 'Britanya Hint Okyanusu Toprakları','code'=>'+246'],
            ['name' => 'جزر فيرجن البريطانية', 'name_tr' => 'İngiliz Virgin Adaları','code'=>'+1 284'],
            ['name' => 'بروناي', 'name_tr' => 'Brunei','code'=>'+673'],
            ['name' => 'بلغاريا', 'name_tr' => 'Bulgaristan','code'=>'+359'],
            ['name' => 'بوركينا فاسو', 'name_tr' => 'Burkina Faso','code'=>'+226'],
            ['name' => 'بوروندي', 'name_tr' => 'Burundi','code'=>'+257'],
            ['name' => 'كمبوديا', 'name_tr' => 'Kamboçya','code'=>'+855'],
            ['name' => 'الكاميرون', 'name_tr' => 'Kamerun','code'=>'+237'],
            ['name' => 'كندا', 'name_tr' => 'Kanada','code'=>'+1'],
            ['name' => 'الرأس الأخضر', 'name_tr' => 'Yeşil Burun Adaları','code'=>'+238'],
            ['name' => 'الكاريبي هولندا', 'name_tr' => 'Karayip Hollandası','code'=>'+599 7'],
            ['name' => 'جزر كايمان', 'name_tr' => 'Cayman Adaları','code'=>'+1 345'],
            ['name' => 'جمهورية افريقيا الوسطى', 'name_tr' => 'Orta Afrika Cumhuriyeti','code'=>'+236'],
            ['name' => 'تشاد', 'name_tr' => 'Çad','code'=>'+235'],
            ['name' => 'تشيلي', 'name_tr' => 'Şili','code'=>'+56'],
            ['name' => 'الصين', 'name_tr' => 'Çin','code'=>'+86'],
            ['name' => 'جزيرة الكريسماس', 'name_tr' => 'Christmas Adası','code'=>'+61'],
            ['name' => 'جزر كوكوس (كيلينغ)', 'name_tr' => 'Cocos (Keeling) Adaları','code'=>'+61'],
            ['name' => 'كولومبيا', 'name_tr' => 'Kolombiya','code'=>'+57'],
            ['name' => 'جزر القمر', 'name_tr' => 'Komorlar','code'=>'+269'],
            ['name' => 'الكونغو - برازافيل', 'name_tr' => 'Kongo - Brazzaville','code'=>'+242'],
            ['name' => 'الكونغو - كينشاسا', 'name_tr' => 'Kongo - Kinşasa','code'=>'+243'],
            ['name' => 'جزر كوك', 'name_tr' => 'Cook Adaları','code'=>'+682'],
            ['name' => 'كوستا ريكا', 'name_tr' => 'Kosta Rika','code'=>'+506'],
            ['name' => 'كوت ديفوار', 'name_tr' => 'Fildişi Sahili','code'=>'+225'],
            ['name' => 'كرواتيا', 'name_tr' => 'Hırvatistan','code'=>'+385'],
            ['name' => 'كوبا', 'name_tr' => 'Küba','code'=>'+53'],
            ['name' => 'كوراساو', 'name_tr' => 'Curacao','code'=>'+599 9'],
            ['name' => 'قبرص', 'name_tr' => 'Kıbrıs','code'=>'+357'],
            ['name' => 'جمهورية التشيك', 'name_tr' => 'Çek Cumhuriyeti','code'=>'+420'],
            ['name' => 'الدنمارك', 'name_tr' => 'Danimarka','code'=>'+45'],
            ['name' => 'دييغو غارسيا', 'name_tr' => 'Diego Garcia','code'=>'+246'],
            ['name' => 'جيبوتي', 'name_tr' => 'Cibuti','code'=>'+253'],
            ['name' => 'دومينيكا', 'name_tr' => 'Dominika','code'=>'+1 767'],
            ['name' => 'جمهورية الدومنيكان', 'name_tr' => 'Dominik Cumhuriyeti','code'=>'+1 809'],
            ['name' => 'جمهورية الدومنيكان', 'name_tr' => 'Dominik Cumhuriyeti','code'=>'+1 829'],
            ['name' => 'جمهورية الدومنيكان', 'name_tr' => 'Dominik Cumhuriyeti','code'=>'+1 849'],
            ['name' => 'الإكوادور', 'name_tr' => 'Ekvador','code'=>'+593'],
            ['name' => 'مصر', 'name_tr' => 'Mısır','code'=>'+20'],
            ['name' => 'السلفادور', 'name_tr' => 'El Salvador','code'=>'+503'],
            ['name' => 'غينيا الإستوائية', 'name_tr' => 'Ekvator Ginesi','code'=>'+240'],
            ['name' => 'إريتريا', 'name_tr' => 'Eritre','code'=>'+291'],
            ['name' => 'استونيا', 'name_tr' => 'Estonya','code'=>'+372'],
            ['name' => 'أثيوبيا', 'name_tr' => 'Etiyopya','code'=>'+251'],
            ['name' => 'جزر فوكلاند', 'name_tr' => 'Falkland Adaları','code'=>'+500'],
            ['name' => 'جزر فاروس', 'name_tr' => 'Faroe Adaları','code'=>'+298'],
            ['name' => 'فيجي', 'name_tr' => 'Fiji','code'=>'+679'],
            ['name' => 'فنلندا', 'name_tr' => 'Finlandiya','code'=>'+358'],
            ['name' => 'فرنسا', 'name_tr' => 'Fransa','code'=>'+33'],
            ['name' => 'غيانا الفرنسية', 'name_tr' => 'Fransız Guyanası','code'=>'+594'],
            ['name' => 'بولينيزيا الفرنسية', 'name_tr' => 'Fransız Polinezyası','code'=>'+689'],
            ['name' => 'الغابون', 'name_tr' => 'Gabon','code'=>'+241'],
            ['name' => 'غامبيا', 'name_tr' => 'Gambiya','code'=>'+220'],
            ['name' => 'جورجيا', 'name_tr' => 'Georgia','code'=>'+995'],
            ['name' => 'ألمانيا', 'name_tr' => 'Almanya','code'=>'+49'],
            ['name' => 'غانا', 'name_tr' => 'Gana','code'=>'+233'],
            ['name' => 'جبل طارق', 'name_tr' => 'Cebelitarık','code'=>'+350'],
            ['name' => 'اليونان', 'name_tr' => 'Yunanistan','code'=>'+30'],
            ['name' => 'الأرض الخضراء', 'name_tr' => 'Yeşil Dünya','code'=>'+299'],
            ['name' => 'غرينادا', 'name_tr' => 'Grenada','code'=>'+1 473'],
            ['name' => 'جوادلوب', 'name_tr' => 'Guadeloupe','code'=>'+590'],
            ['name' => 'غوام', 'name_tr' => 'Guam','code'=>'+1 671'],
            ['name' => 'غواتيمالا', 'name_tr' => 'Guatemala','code'=>'+502'],
            ['name' => 'غيرنسي', 'name_tr' => 'bir tür inek','code'=>'+44'],
            ['name' => 'غينيا', 'name_tr' => 'Gine','code'=>'+224'],
            ['name' => 'غينيا بيساو', 'name_tr' => 'Gine-Bissau','code'=>'+245'],
            ['name' => 'غيانا', 'name_tr' => 'Guyana','code'=>'+592'],
            ['name' => 'هايتي', 'name_tr' => 'Haiti','code'=>'+509'],
            ['name' => 'هندوراس', 'name_tr' => 'Honduras','code'=>'+504'],
            ['name' => 'هونج كونج SAR الصين', 'name_tr' => 'Hong Kong SAR Çin','code'=>'+852'],
            ['name' => 'هنغاريا', 'name_tr' => 'Macaristan','code'=>'+36'],
            ['name' => 'أيسلندا', 'name_tr' => 'İzlanda','code'=>'+354'],
            ['name' => 'الهند', 'name_tr' => 'Hindistan','code'=>'+91'],
            ['name' => 'إندونيسيا', 'name_tr' => 'Endonezya','code'=>'+62'],
            ['name' => 'إيران', 'name_tr' => 'İran','code'=>'+98'],
            ['name' => 'العراق', 'name_tr' => 'Irak','code'=>'+964'],
            ['name' => 'أيرلندا', 'name_tr' => 'İrlanda','code'=>'+353'],
            ['name' => 'الكيان الصهيوني', 'name_tr' => 'İsrail-Siyonist varlık','code'=>'+972'],
            ['name' => 'إيطاليا', 'name_tr' => 'İtalya','code'=>'+39'],
            ['name' => 'جامايكا', 'name_tr' => 'Jamaika','code'=>'+1 876'],
            ['name' => 'اليابان', 'name_tr' => 'Japonya','code'=>'+81'],
            ['name' => 'جيرسي', 'name_tr' => 'Jersey','code'=>'+44'],
            ['name' => 'الأردن', 'name_tr' => 'Ürdün','code'=>'+962'],
            ['name' => 'كازاخستان', 'name_tr' => 'Kazakistan','code'=>'+7 6'],
            ['name' => 'كازاخستان', 'name_tr' => 'Kazakistan','code'=>'+7 7'],
            ['name' => 'كينيا', 'name_tr' => 'Kenya','code'=>'+254'],
            ['name' => 'كيريباس', 'name_tr' => 'Kiribati','code'=>'+686'],
            ['name' => 'الكويت', 'name_tr' => 'Kuveyt','code'=>'+965'],
            ['name' => 'قرغيزستان', 'name_tr' => 'Kırgızistan','code'=>'+996'],
            ['name' => 'لاوس', 'name_tr' => 'Laos','code'=>'+856'],
            ['name' => 'لاتفيا', 'name_tr' => 'Letonya','code'=>'+371'],
            ['name' => 'لبنان', 'name_tr' => 'Lübnan','code'=>'+961'],
            ['name' => 'ليسوتو', 'name_tr' => 'Lesotho','code'=>'+266'],
            ['name' => 'ليبيريا', 'name_tr' => 'Liberya','code'=>'+231'],
            ['name' => 'ليبيا', 'name_tr' => 'Libya','code'=>'+218'],
            ['name' => 'ليختنشتاين', 'name_tr' => 'Lihtenştayn','code'=>'+423'],
            ['name' => 'ليتوانيا', 'name_tr' => 'Litvanya','code'=>'+370'],
            ['name' => 'لوكسمبورغ', 'name_tr' => 'Lüksemburg','code'=>'+352'],
            ['name' => 'ماكاو SAR الصين', 'name_tr' => 'Makao SAR Çin','code'=>'+853'],
            ['name' => 'مقدونيا', 'name_tr' => 'Makedonya','code'=>'+389'],
            ['name' => 'مدغشقر', 'name_tr' => 'Madagaskar','code'=>'+261'],
            ['name' => 'مالاوي', 'name_tr' => 'Malawi','code'=>'+265'],
            ['name' => 'ماليزيا', 'name_tr' => 'Malezya','code'=>'+60'],
            ['name' => 'جزر المالديف', 'name_tr' => 'Maldivler','code'=>'+960'],
            ['name' => 'مالي', 'name_tr' => 'mali','code'=>'+223'],
            ['name' => 'مالطا', 'name_tr' => 'Malta','code'=>'+356'],
            ['name' => 'جزر مارشال', 'name_tr' => 'Marshall Adaları','code'=>'+692'],
            ['name' => 'مارتينيك', 'name_tr' => 'Martinik','code'=>'+596'],
            ['name' => 'موريتانيا', 'name_tr' => 'Moritanya','code'=>'+222'],
            ['name' => 'موريشيوس', 'name_tr' => 'Mauritius','code'=>'+230'],
            ['name' => 'مايوت', 'name_tr' => 'Mayotte','code'=>'+262'],
            ['name' => 'المكسيك', 'name_tr' => 'Meksika','code'=>'+52'],
            ['name' => 'ميكرونيزيا', 'name_tr' => 'Mikronezya','code'=>'+691'],
            ['name' => 'مولدوفا', 'name_tr' => 'Moldova','code'=>'+373'],
            ['name' => 'موناكو', 'name_tr' => 'Monako','code'=>'+377'],
            ['name' => 'منغوليا', 'name_tr' => 'Moğolistan','code'=>'+976'],
            ['name' => 'الجبل الأسود', 'name_tr' => 'Karadağ','code'=>'+382'],
            ['name' => 'مونتسيرات', 'name_tr' => 'Montserrat','code'=>'+1 664'],
            ['name' => 'المغرب', 'name_tr' => 'Fas','code'=>'+212'],
            ['name' => 'موزمبيق', 'name_tr' => 'Mozambik','code'=>'+258'],
            ['name' => 'ميانمار (بورما)', 'name_tr' => 'Myanmar (Burma)','code'=>'+95'],
            ['name' => 'ناميبيا', 'name_tr' => 'Namibya','code'=>'+264'],
            ['name' => 'ناورو', 'name_tr' => 'Nauru','code'=>'+674'],
            ['name' => 'نيبال', 'name_tr' => 'Nepal','code'=>'+977'],
            ['name' => 'هولندا', 'name_tr' => 'Hollanda','code'=>'+31'],
            ['name' => 'كاليدونيا الجديدة', 'name_tr' => 'Yeni Kaledonya','code'=>'+687'],
            ['name' => 'نيوزيلاندا', 'name_tr' => 'Yeni Zelanda','code'=>'+64'],
            ['name' => 'نيكاراغوا', 'name_tr' => 'Nikaragua','code'=>'+505'],
            ['name' => 'النيجر', 'name_tr' => 'Nijer','code'=>'+227'],
            ['name' => 'نيجيريا', 'name_tr' => 'Nijerya','code'=>'+234'],
            ['name' => 'نيوي', 'name_tr' => 'Niue','code'=>'+683'],
            ['name' => 'جزيرة نورفولك', 'name_tr' => 'Norfolk Adası','code'=>'+672'],
            ['name' => 'كوريا الشماليه', 'name_tr' => 'Kuzey Kore','code'=>'+850'],
            ['name' => 'جزر مريانا الشمالية', 'name_tr' => 'Kuzey Mariana Adaları','code'=>'+1 670'],
            ['name' => 'النرويج', 'name_tr' => 'Norveç','code'=>'+47'],
            ['name' => 'سلطنة عمان', 'name_tr' => 'Amman Krallığı','code'=>'+968'],
            ['name' => 'باكستان', 'name_tr' => 'Pakistan','code'=>'+92'],
            ['name' => 'بالاو', 'name_tr' => 'Palau','code'=>'+680'],
            ['name' => 'فلسطين', 'name_tr' => 'Filistin','code'=>'+970'],
            ['name' => 'بناما', 'name_tr' => 'Panama','code'=>'+507'],
            ['name' => 'بابوا غينيا الجديدة', 'name_tr' => 'Papua Yeni Gine','code'=>'+675'],
            ['name' => 'باراغواي', 'name_tr' => 'Paraguay','code'=>'+595'],
            ['name' => 'بيرو', 'name_tr' => 'Peru','code'=>'+51'],
            ['name' => 'الفلبين', 'name_tr' => 'Filipinler','code'=>'+63'],
            ['name' => 'جزر بيتكيرن', 'name_tr' => 'Pitcairn Adaları','code'=>'+64'],
            ['name' => 'بولندا', 'name_tr' => 'Polonya','code'=>'+48'],
            ['name' => 'البرتغال', 'name_tr' => 'Portekiz','code'=>'+351'],
            ['name' => 'بورتوريكو', 'name_tr' => 'Porto Riko','code'=>'+1 787'],
            ['name' => 'بورتوريكو', 'name_tr' => 'Porto Riko','code'=>'+1 939'],
            ['name' => 'دولة قطر', 'name_tr' => 'Katar Devleti','code'=>'+974'],
            ['name' => 'جمع شمل', 'name_tr' => 'birleşme','code'=>'+262'],
            ['name' => 'رومانيا', 'name_tr' => 'Romanya','code'=>'+40'],
            ['name' => 'روسيا', 'name_tr' => 'Rusya','code'=>'+7'],
            ['name' => 'رواندا', 'name_tr' => 'Ruanda','code'=>'+250'],
            ['name' => 'ساموا', 'name_tr' => 'Samoa','code'=>'+685'],
            ['name' => 'سان مارينو', 'name_tr' => 'San Marino','code'=>'+378'],
            ['name' => 'ساو تومي برينسيبي', 'name_tr' => 'Sao Tome Principe','code'=>'+239'],
            ['name' => 'المملكة العربية السعودية', 'name_tr' => 'Suudi Arabistan','code'=>'+966'],
            ['name' => 'السنغال', 'name_tr' => 'Senegal','code'=>'+221'],
            ['name' => 'صربيا', 'name_tr' => 'Sırbistan','code'=>'+381'],
            ['name' => 'سيشيل', 'name_tr' => 'Seyşeller','code'=>'+248'],
            ['name' => 'سيرا ليون', 'name_tr' => 'Serra Leon','code'=>'+232'],
            ['name' => 'سنغافورة', 'name_tr' => 'Singapur','code'=>'+65'],
            ['name' => 'سينت أوستاتيوس', 'name_tr' => 'Saint Eustatius','code'=>'+599 3'],
            ['name' => 'سينت مارتن', 'name_tr' => 'Saint Martin','code'=>'+1 721'],
            ['name' => 'سلوفاكيا', 'name_tr' => 'Slovakya','code'=>'+421'],
            ['name' => 'سلوفينيا', 'name_tr' => 'Slovenya','code'=>'+386'],
            ['name' => 'جزر سليمان', 'name_tr' => 'Solomon Adaları','code'=>'+677'],
            ['name' => 'الصومال', 'name_tr' => 'Somali','code'=>'+252'],
            ['name' => 'جنوب أفريقيا', 'name_tr' => 'güney Afrika','code'=>'+27'],
            ['name' => 'جورجيا الجنوبية جزر ساندويتش الجنوبية', 'name_tr' => 'Güney Georgia ve Güney Sandwich A','code'=>'+500'],
            ['name' => 'كوريا الجنوبية', 'name_tr' => 'Güney Kore','code'=>'+82'],
            ['name' => 'أوسيتيا الجنوبية', 'name_tr' => 'Güney Osetya','code'=>'+995 34'],
            ['name' => 'جنوب السودان', 'name_tr' => 'Güney Sudan','code'=>'+211'],
            ['name' => 'إسبانيا', 'name_tr' => 'İspanya','code'=>'+34'],
            ['name' => 'سيريلانكا', 'name_tr' => 'Sri Lanka','code'=>'+94'],
            ['name' => 'سانت بارتيليمي', 'name_tr' => 'St. Barthelemy','code'=>'+590'],
            ['name' => 'سانت هيلانة', 'name_tr' => 'St. Helena','code'=>'+290'],
            ['name' => 'سانت كيتس نيفيس', 'name_tr' => 'Saint Kitts Nevis','code'=>'+1 869'],
            ['name' => 'شارع لوسيا', 'name_tr' => 'Lucia Caddesi','code'=>'+1 758'],
            ['name' => 'سانت مارتن (فرنسا)', 'name_tr' => 'Saint Martin (Fransa)','code'=>'+590'],
            ['name' => 'سانت بيير وميكلون', 'name_tr' => 'St. Pierre ve Miquelon','code'=>'+508'],
            ['name' => 'سانت فنسنت وجزر غرينادين', 'name_tr' => 'Saint Vincent ve Grenadinler','code'=>'+1 784'],
            ['name' => 'السودان', 'name_tr' => 'Sudan','code'=>'+249'],
            ['name' => 'سورينام', 'name_tr' => 'Surinam','code'=>'+597'],
            ['name' => 'سفالبارد', 'name_tr' => 'Svalbard','code'=>'+47 79'],
            ['name' => 'سفالبارد جان ماين', 'name_tr' => 'Svalbard Jan Mayen','code'=>'+47 79'],
            ['name' => 'سوازيلاند', 'name_tr' => 'Svaziland','code'=>'+268'],
            ['name' => 'السويد', 'name_tr' => 'İsveç','code'=>'+46'],
            ['name' => 'سويسرا', 'name_tr' => 'İsviçre','code'=>'+41'],
            ['name' => 'سوريا', 'name_tr' => 'Suriye','code'=>'+963'],
            ['name' => 'تايوان', 'name_tr' => 'Tayvan','code'=>'+886'],
            ['name' => 'طاجيكستان', 'name_tr' => 'Tacikistan','code'=>'+992'],
            ['name' => 'تنزانيا', 'name_tr' => 'Tanzanya','code'=>'+255'],
            ['name' => 'تايلاند', 'name_tr' => 'Tayland','code'=>'+66'],
            ['name' => 'تيمور الشرقية', 'name_tr' => 'Doğu Timor','code'=>'+670'],
            ['name' => 'توجو', 'name_tr' => 'Togo','code'=>'+228'],
            ['name' => 'توكيلاو', 'name_tr' => 'Tokelau','code'=>'+690'],
            ['name' => 'تونغا', 'name_tr' => 'Tonga','code'=>'+676'],
            ['name' => 'ترينيداد وتوباجو', 'name_tr' => 'Trinidad ve Tobago','code'=>'+1 868'],
            ['name' => 'تونس', 'name_tr' => 'Tunus','code'=>'+216'],
            ['name' => 'ديك رومي', 'name_tr' => 'Türkiye','code'=>'+90'],
            ['name' => 'تركمانستان', 'name_tr' => 'Türkmenistan','code'=>'+993'],
            ['name' => 'جزر تركس كايكوس', 'name_tr' => 'Turks ve Caicos Adaları','code'=>'+1 649'],
            ['name' => 'توفالو', 'name_tr' => 'Tuvalu','code'=>'+688'],
            ['name' => 'جزر فيرجن الأمريكية', 'name_tr' => 'ABD Virjin Adaları','code'=>'+1 340'],
            ['name' => 'أوغندا', 'name_tr' => 'Uganda','code'=>'+256'],
            ['name' => 'أوكرانيا', 'name_tr' => 'Ukrayna','code'=>'+380'],
            ['name' => 'الإمارات العربية المتحدة', 'name_tr' => 'Birleşik Arap Emirlikleri','code'=>'+971'],
            ['name' => 'المملكة المتحدة', 'name_tr' => 'İngiltere','code'=>'+44'],
            ['name' => 'الولايات المتحدة الأمريكية', 'name_tr' => 'Amerika Birleşik Devletleri','code'=>'+1'],
            ['name' => 'أوروغواي', 'name_tr' => 'Uruguay','code'=>'+598'],
            ['name' => 'أوزبكستان', 'name_tr' => 'Özbekistan','code'=>'+998'],
            ['name' => 'فانواتو', 'name_tr' => 'Vanuatu','code'=>'+678'],
            ['name' => 'مدينة الفاتيكان', 'name_tr' => 'Vatikan','code'=>'+39 06 698'],
            ['name' => 'مدينة الفاتيكان', 'name_tr' => 'Vatikan','code'=>'+379'],
            ['name' => 'فنزويلا', 'name_tr' => 'Venezuela','code'=>'+58'],
            ['name' => 'فيتنام', 'name_tr' => 'Vietnam','code'=>'+84'],
            ['name' => 'واليس فوتونا', 'name_tr' => 'Wallis Futuna','code'=>'+681'],
            ['name' => 'اليمن', 'name_tr' => 'Yemen','code'=>'+967'],
            ['name' => 'زامبيا', 'name_tr' => 'Zambiya','code'=>'+260'],
            ['name' => 'زنجبار', 'name_tr' => 'Zanzibar','code'=>'+255'],
        ]);
    }
}
