<?php

use Illuminate\Database\Seeder;

class DiseaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('diseases')->insert([
            ['name' => 'ارتجاج في المخ', 'name_tr' => 'Beyin Sarsıntısı'],
            ['name' => 'ازدواجية شخصية', 'name_tr' => 'Şizofren'],
            ['name' => 'ازمة صدرية', 'name_tr' => 'GÖĞÜS AĞRISI'],
            ['name' => 'اسهال', 'name_tr' => 'ishal '],
            ['name' => 'اضطراب بالنمو', 'name_tr' => 'YAYGIN GELİŞİMSEL BOZUKLUK'],
            ['name' => 'اعصاب', 'name_tr' => 'SİNİR'],
            ['name' => 'اغماء، غشيان', 'name_tr' => 'Bayılmak'],
            ['name' => 'اكتئاب', 'name_tr' => ' manik depresif '],
            ['name' => 'اكتئاب و هوس', 'name_tr' => 'Depresyon ve manik depresif hastalık'],
            ['name' => 'التهاب شعبي حاد', 'name_tr' => 'bronşit '],
            ['name' => 'التهاب قولون', 'name_tr' => 'kalın bağırsak iltihabi'],
            ['name' => 'التهاب مفاصل', 'name_tr' => 'arterit'],
            ['name' => 'التواء', 'name_tr' => ' burkulma'],
            ['name' => 'العقل الواعي، المنطقي', 'name_tr' => 'Şuur, bilinç (Rasyonel)'],
            ['name' => 'الم عصبي', 'name_tr' => 'NEVRALJİ'],
            ['name' => 'امراض جلدية', 'name_tr' => 'Cildiye Hastalığı'],
            ['name' => 'انزلاق غضروفي', 'name_tr' => 'OMURGE EĞRİLİĞİ'],
            ['name' => 'انسداد الشرايين', 'name_tr' => 'damar tıkanmas'],
            ['name' => 'انسداد رئوي', 'name_tr' => 'Kronik Obstrüktif Akciğer Hastalığı'],
            ['name' => 'انطوائي', 'name_tr' => 'Otizm'],
            ['name' => 'انفصام', 'name_tr' => 'şizofreni '],
            ['name' => 'انفلونزا', 'name_tr' => 'grip '],
            ['name' => 'أبرص', 'name_tr' => 'Cüzamlı'],
            ['name' => 'أذن وسطى', 'name_tr' => 'Orta kulak '],
            ['name' => 'أعرج', 'name_tr' => 'topal '],
            ['name' => 'أمعاء دقيقة', 'name_tr' => 'ince bağırsak'],
            ['name' => 'أمعاء غليظة', 'name_tr' => 'kalın bağısak'],
            ['name' => 'أورام', 'name_tr' => 'KAPARMA'],
            ['name' => 'بُلعوم', 'name_tr' => 'yutak '],
            ['name' => 'بتر', 'name_tr' => 'AMPÜTASYON'],
            ['name' => 'بدانة', 'name_tr' => 'şişmanlık'],
            ['name' => 'بروستاتا', 'name_tr' => ' Prostat'],
            ['name' => 'بلغم', 'name_tr' => 'balgam'],
            ['name' => 'تاكل مفاصل الحوض', 'name_tr' => 'kemiğin avasküler nekrozu'],
            ['name' => 'تأخر النطق', 'name_tr' => 'Konuşma Gecikmesi'],
            ['name' => 'تجلط الدم', 'name_tr' => 'Koagülasyon; pıhtılaşma '],
            ['name' => 'تخمة', 'name_tr' => 'Mide fesadı'],
            ['name' => 'تشنج', 'name_tr' => 'Konvülziyon'],
            ['name' => 'تشوه خلقي', 'name_tr' => 'yaratılış bozukluğu'],
            ['name' => 'تضخم كلى', 'name_tr' => 'nefromegali'],
            ['name' => 'تضيق في القصبات - حساسية', 'name_tr' => 'Kua'],
            ['name' => 'تقدم في العمر', 'name_tr' => 'Yaşın artması'],
            ['name' => 'تقلص عضلي', 'name_tr' => 'kas krampları'],
            ['name' => 'تقيؤ', 'name_tr' => 'kusma '],
            ['name' => 'تكسر الدم', 'name_tr' => 'hemolitik anemi'],
            ['name' => 'تلاثيميا', 'name_tr' => 'Talasemi'],
            ['name' => 'تلوث او تسمم الدم', 'name_tr' => 'septisemi / Bakteriyemi '],
            ['name' => 'تليف رئتين', 'name_tr' => 'PULMONER FİBROZİS'],
            ['name' => 'تليف كبد', 'name_tr' => 'Karaciğer Fibrozisi '],
            ['name' => 'توتر', 'name_tr' => 'Gerginlik'],
            ['name' => 'توحد', 'name_tr' => 'OTİZM HASTALIĞI'],
            ['name' => 'جُدري', 'name_tr' => 'çiçek hastalığı '],
            ['name' => 'جراحة تجميلية', 'name_tr' => 'Estetik '],
            ['name' => 'جرب', 'name_tr' => ' uyuz'],
            ['name' => 'جرب، حكة', 'name_tr' => 'Uyuz'],
            ['name' => 'جلطة', 'name_tr' => 'PIHTI'],
            ['name' => 'جلطة دماغية دموية', 'name_tr' => 'BEYİN KAN PIHTISI'],
            ['name' => 'جلطة دموية', 'name_tr' => 'kan pıhtısı '],
            ['name' => 'جنون', 'name_tr' => 'Akılsız, deli'],
            ['name' => 'جيوب', 'name_tr' => 'Sinozit '],
            ['name' => 'حجامة', 'name_tr' => 'Hacamatçılık, kanamla sanatı'],
            ['name' => 'حرق', 'name_tr' => 'YANIK'],
            ['name' => 'حساسية', 'name_tr' => 'ALERJİ'],
            ['name' => 'حصبة', 'name_tr' => 'kızamık '],
            ['name' => 'حماق، جدري الماء', 'name_tr' => 'su çiçeği '],
            ['name' => 'حمى الدريس', 'name_tr' => 'saman nezlesi'],
            ['name' => 'حمى شوكية - التهاب السحايا', 'name_tr' => 'Menenjit'],
            ['name' => 'حمى صفراء', 'name_tr' => 'sarı humma'],
            ['name' => 'خلع ولادة', 'name_tr' => 'Doğumsal Kalça Çıkığı\n\n\n'],
            ['name' => 'دوالي', 'name_tr' => 'Varis '],
            ['name' => 'ذئبة حمراء', 'name_tr' => 'Sistemik lupus eritematozusun '],
            ['name' => 'رباط صليبي', 'name_tr' => 'çapraz bağ '],
            ['name' => 'ربو', 'name_tr' => 'astım '],
            ['name' => 'ربو تشعبي', 'name_tr' => 'bronşiyal astım'],
            ['name' => 'رعاش', 'name_tr' => 'Parkinson'],
            ['name' => 'رهاب', 'name_tr' => 'Fobiler '],
            ['name' => 'روماتيد', 'name_tr' => 'Romatizmal'],
            ['name' => 'روماتيزم', 'name_tr' => 'romatizma'],
            ['name' => 'روماتيود المفاصل', 'name_tr' => 'Romatoid artrit'],
            ['name' => 'رئة', 'name_tr' => 'akciğer '],
            ['name' => 'زائدة', 'name_tr' => 'Apandisit'],
            ['name' => 'زكام، رشح', 'name_tr' => 'nezle'],
            ['name' => 'زواج احفاد', 'name_tr' => 'TORUN EVLİLİKLERİ'],
            ['name' => 'سرطان', 'name_tr' => 'KANSER'],
            ['name' => 'سرطان أمعاء', 'name_tr' => 'Bağırsak kanseri'],
            ['name' => 'سرطان ثدي', 'name_tr' => 'meme kanseri'],
            ['name' => 'سرطان جلدي', 'name_tr' => 'CİLT KANSERİ '],
            ['name' => 'سرطان حنجرة', 'name_tr' => 'girtlak kanseri'],
            ['name' => 'سرطان دم', 'name_tr' => 'KAN KANSERİ'],
            ['name' => 'سرطان قولون', 'name_tr' => 'Kolon kanser\''],
            ['name' => 'سعال', 'name_tr' => 'Öksürük'],
            ['name' => 'سكتة قلبية', 'name_tr' => 'kalp krizi'],
            ['name' => 'سكري', 'name_tr' => 'DİYABET'],
            ['name' => 'سل', 'name_tr' => 'TÜBERKÜLOZ'],
            ['name' => 'سلس البول', 'name_tr' => 'Bağırsak inkontinansı'],
            ['name' => 'سلس براز', 'name_tr' => 'Dışkı kaçırma'],
            ['name' => 'سمنة', 'name_tr' => 'OBEZİTE'],
            ['name' => 'سوء تغذية', 'name_tr' => 'malnütrisyon'],
            ['name' => 'سوء/عسر الهضم', 'name_tr' => 'hazımsızlık'],
            ['name' => 'شراهة', 'name_tr' => 'Oburluk'],
            ['name' => 'شلل', 'name_tr' => 'felç '],
            ['name' => 'شلل أطفال', 'name_tr' => 'çocuk felci '],
            ['name' => 'شيخوخة', 'name_tr' => 'YAŞLILIK'],
            ['name' => 'صداع', 'name_tr' => 'baş ağrısı '],
            ['name' => 'صداع نصفي', 'name_tr' => 'MİGREN'],
            ['name' => 'صداع نصفي - شقيقة', 'name_tr' => 'Migren'],
            ['name' => 'صدف', 'name_tr' => 'Sedef '],
            ['name' => 'صدفية', 'name_tr' => 'SEDEF HASTALIĞI'],
            ['name' => 'صدمة', 'name_tr' => 'Şok '],
            ['name' => 'صرع', 'name_tr' => 'ELPİLEPSİ'],
            ['name' => 'ضعف اللغة و الكلام', 'name_tr' => 'DİL VE KONUŞMA BOZUKLUĞU'],
            ['name' => 'ضغط', 'name_tr' => ' tansiyon'],
            ['name' => 'ضغط وسكري', 'name_tr' => 'TANISYON VE ŞEKER'],
            ['name' => 'ضمور اعصاب', 'name_tr' => 'Sinir atrofisi'],
            ['name' => 'ضمور عقل', 'name_tr' => 'Beyin atrofisi'],
            ['name' => 'ضيق نفس', 'name_tr' => 'NEFES DARLIĞI'],
            ['name' => 'طب الأسنان', 'name_tr' => 'diş hekimi '],
            ['name' => 'طحال', 'name_tr' => 'dalak '],
            ['name' => 'طفح جلدي، حكة', 'name_tr' => ' kaşıntı'],
            ['name' => 'عجز', 'name_tr' => ' İmpotans'],
            ['name' => 'عطاس', 'name_tr' => 'hapşırmak '],
            ['name' => 'عظمية', 'name_tr' => 'Ortopedi - '],
            ['name' => 'عقم', 'name_tr' => 'Kısırlık'],
            ['name' => 'علاج كهربائي', 'name_tr' => 'Fizik tedavi'],
            ['name' => 'غازات في المعدة', 'name_tr' => 'Gastrit'],
            ['name' => 'غدة درقية', 'name_tr' => 'TİROİD'],
            ['name' => 'غدة لعابية', 'name_tr' => 'tükürük bezleri '],
            ['name' => 'غدة نخامية', 'name_tr' => 'hipofizi pitüiter bez '],
            ['name' => 'غسيل كلى', 'name_tr' => 'Diyaliz '],
            ['name' => 'غضروف', 'name_tr' => 'KIKIRDAK'],
            ['name' => 'غياب وعي، فقدان ذاكرة', 'name_tr' => 'Komaya girmek; Alzayemır'],
            ['name' => 'فتق، فتوق', 'name_tr' => 'Fıtık'],
            ['name' => 'فحص طبي', 'name_tr' => 'tipi muayene '],
            ['name' => 'فشل كلوي', 'name_tr' => 'BÖBREK YETMEZLİĞİ '],
            ['name' => 'فصام، إزدواجية شخصية', 'name_tr' => 'şizofreni '],
            ['name' => 'فقدان ذاكرة', 'name_tr' => 'Alzheimer '],
            ['name' => 'فقر الدم - انيميا  الوراثي', 'name_tr' => 'Talasemi'],
            ['name' => 'فقر دم', 'name_tr' => 'ANEMİ'],
            ['name' => 'قرحة', 'name_tr' => ' ülser'],
            ['name' => 'قرحة المعدة', 'name_tr' => 'ülser; mide hastalığı '],
            ['name' => 'قصر نظر', 'name_tr' => 'MİYOPİ'],
            ['name' => 'قصور نخاع العظم المكتسب', 'name_tr' => ' Edinsel Kemik iliği yetmezlikleri'],
            ['name' => 'قفص صدري', 'name_tr' => 'toraks '],
            ['name' => 'قلب', 'name_tr' => 'KALP'],
            ['name' => 'قلق', 'name_tr' => 'anksiyete; endişe '],
            ['name' => 'قلق ، اضطراب نفسي', 'name_tr' => 'Psikolojik hastalık'],
            ['name' => 'قيئ', 'name_tr' => 'Kusmak'],
            ['name' => 'كبد', 'name_tr' => 'karaciğer'],
            ['name' => 'كبد وبائي', 'name_tr' => 'HEPATİT'],
            ['name' => 'كتف', 'name_tr' => 'omuz '],
            ['name' => 'كسر', 'name_tr' => 'kırık '],
            ['name' => 'كسر حوض', 'name_tr' => 'Avasküler Nekroz'],
            ['name' => 'كلوي مزمن', 'name_tr' => 'KRONİK BÖBEK'],
            ['name' => 'كلى', 'name_tr' => 'BÖBREK'],
            ['name' => 'لثة', 'name_tr' => 'dişeti '],
            ['name' => 'لوكيميا', 'name_tr' => 'Lösemiler'],
            ['name' => 'مخيخ', 'name_tr' => 'Beyincik-'],
            ['name' => 'مرارة', 'name_tr' => 'Safra kesesi '],
            ['name' => 'مرض عصبي', 'name_tr' => 'Sinir hastalığı'],
            ['name' => 'مريض نفسي', 'name_tr' => 'PSİKOLOJİ HASTASI'],
            ['name' => 'مرئ', 'name_tr' => 'Yemek borusu ( özefakos ) '],
            ['name' => 'مصران اعور', 'name_tr' => 'Apantest'],
            ['name' => 'معاق بالتعلم', 'name_tr' => 'Özgül öğrenme güçlüğü'],
            ['name' => 'معاق تشنج', 'name_tr' => 'SPASTİK ENGELLİ'],
            ['name' => 'معاق/ة', 'name_tr' => 'ENGELLİ'],
            ['name' => 'معاق/ة بصرياً', 'name_tr' => 'GÖRME ENGELLİ'],
            ['name' => 'معاق/ة حركياً', 'name_tr' => 'FİZİKSEL ENGELLİ'],
            ['name' => 'معاق/ة سمعياً', 'name_tr' => 'İŞİTME ENGELLİ'],
            ['name' => 'معاق/ة عقلياً', 'name_tr' => 'ZİHNİSEL ENGELLİ'],
            ['name' => 'معالجة بالاشعاع', 'name_tr' => 'RADYOTERAPİ'],
            ['name' => 'معدة', 'name_tr' => 'mide '],
            ['name' => 'مغص', 'name_tr' => 'karın ağrısı '],
            ['name' => 'منغولي/ة', 'name_tr' => 'MOĞOL'],
            ['name' => 'مياه في الرئتين', 'name_tr' => 'Akciğer Ödemi'],
            ['name' => 'نسيان', 'name_tr' => 'Unutkanlık'],
            ['name' => 'نقص سكر الدم', 'name_tr' => 'hipoglisem'],
            ['name' => 'نقص مناعة', 'name_tr' => 'İMMÜN YETMEZLİK'],
            ['name' => 'نقص هرمون النمو', 'name_tr' => 'büyüme hormonu eksikliği '],
            ['name' => 'هشاشة عظام', 'name_tr' => 'OSTEOPOROZ'],
            ['name' => 'هظم', 'name_tr' => 'Sindirmek'],
            ['name' => 'وراثي', 'name_tr' => 'genetik '],
            ['name' => 'ورم', 'name_tr' => 'tümör'],
            ['name' => 'ورم سرطاني', 'name_tr' => 'KANSER TÜMÖRÜ'],
            ['name' => 'ورم غدد', 'name_tr' => 'ADENOMA'],
            ['name' => 'ورم في الدماغ', 'name_tr' => 'Beyin tümörü'],
            ['name' => 'ورم ليفي', 'name_tr' => 'LİFLİ TÜMÖR'],
            ['name' => 'ورم، اورام', 'name_tr' => 'Ur, şişlik'],
            ['name' => 'وسواس قهري', 'name_tr' => 'obsesif kompulsif bozukluk hastalıklarından '],
        ]);
    }
}
