<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /*$user_id = DB::table('users')->insertGetId([
            'full_name' => 'الادمن',
            'first_name' => 'admin',
            'user_name' => 'admin',
            'email' => 'admin@gmail.com',
            'password' => bcrypt('12345678'),
        ]);*/

        \App\User::create([
            'first_name' => "هاني",
            'second_name' => "محمد",
            'third_name' => "عودة",
            'family_name' => "الاغا",
            'full_name' => 'هاني محمد عودة الاغا',
            'user_name' => "",
            'email' => 'gaza@yardimeli.org.tr',
            'email_verified_at' => NULL,
            'password' => '$2y$10$9P39J8Vj9OUpu2URJ4SiMerXjOvBiBGEWg7GgWrDS36lGRg92J0oS',
            'work_start_date' => '2009-05-01',
            'date_of_birth' => '1975-08-04',
            'id_number' => 900894734,
            'mobile' => NULL,
            'mobile_one' => 599038380,
            'mobile_two' => NULL,
            'address' => 'شارع جامعة الدول العربية - خلف بنك فلسطين',
            'contract_type' => 'دائم',
            'remember_token' => NULL,
            'created_at' => '2019-09-25 10:43:43',
            'updated_at' => '2019-09-25 10:43:43',
            'deleted_at' => NULL,
            'neighborhood_id' => 108,
            'department_id' => 1,
            'social_status_id' => 8,
            'university_specialty_id' => 2,
            'created_by' => NULL,
            'updated_by' => NULL,
            'deleted_by' => NULL
        ]);

        \App\User::create([
            'first_name' => "هاشم",
            'second_name' => "ناهض",
            'third_name' => "هاشم",
            'family_name' => "الترك",
            'full_name' => 'هاشم  ناهض هاشم الترك',
            'user_name' => "",
            'email' => NULL,
            'email_verified_at' => NULL,
            'password' => '$2y$10$McetYMqbUCueNlitSIjtUuJlxIRNuTtMvhMJTsIAfVzPzTxxpagBS',
            'work_start_date' => '2010-02-01',
            'date_of_birth' => '1988-08-08',
            'id_number' => 802034033,
            'mobile' => NULL,
            'mobile_one' => 595915517,
            'mobile_two' => 599696369,
            'address' => 'شارع المغربي بالقرب من مسجد بلبل',
            'contract_type' => 'دائم',
            'remember_token' => NULL,
            'created_at' => '2019-09-25 10:43:43',
            'updated_at' => '2019-09-25 10:43:43',
            'deleted_at' => NULL,
            'neighborhood_id' => 92,
            
            'department_id' => 2,
            'social_status_id' => 8,
            'university_specialty_id' => 3,
            'created_by' => NULL,
            'updated_by' => NULL,
            'deleted_by' => NULL
        ]);

        \App\User::create([
            'first_name' => "هلا",
            'second_name' => "زهير",
            'third_name' => "عدنان",
            'family_name' => "العشي",
            'full_name' => 'هلا زهير عدنان العشي',
            'user_name' => "",
            'email' => 'hala-ashi@hotmail.com',
            'email_verified_at' => NULL,
            'password' => '$2y$10$klp3xhw7V1UH76UVPR/V8.74ioiZ2pxtvesv.w.yHhnuQ9RJXsO/a',
            'work_start_date' => '2010-04-15',
            'date_of_birth' => '1987-02-09',
            'id_number' => 800650624,
            'mobile' => 2875212,
            'mobile_one' => 597733408,
            'mobile_two' => 599853526,
            'address' => 'شارع محمد جمجوم بالقرب من صيدلية مسلم',
            'contract_type' => 'دائم',
            'remember_token' => NULL,
            'created_at' => '2019-09-25 10:43:43',
            'updated_at' => '2019-09-25 10:43:43',
            'deleted_at' => NULL,
            'neighborhood_id' => 252,
            
            'department_id' => 3,
            'social_status_id' => 5,
            'university_specialty_id' => 4,
            'created_by' => NULL,
            'updated_by' => NULL,
            'deleted_by' => NULL
        ]);

        \App\User::create([
            'first_name' => "عمار",
            'second_name' => "محمود",
            'third_name' => "شعبان",
            'family_name' => "الحلو",
            'full_name' => 'عمار محمود شعبان الحلو',
            'user_name' => "",
            'email' => 'ameer.30-30@hotmail.com',
            'email_verified_at' => NULL,
            'password' => '$2y$10$AtIVtHQpKeTs8KbWUdlWCOO1SFjTaASZrsLwbnO8MaWSMdIlJeklu',
            'work_start_date' => '2013-05-15',
            'date_of_birth' => '1989-11-21',
            'id_number' => 802524452,
            'mobile' => NULL,
            'mobile_one' => 598781516,
            'mobile_two' => 598495150,
            'address' => 'شارع الحلو بجوار مفترق الشهداء',
            'contract_type' => 'دائم',
            'remember_token' => NULL,
            'created_at' => '2019-09-25 10:43:43',
            'updated_at' => '2019-09-25 10:43:43',
            'deleted_at' => NULL,
            'neighborhood_id' => 2,
            
            'department_id' => 4,
            'social_status_id' => 5,
            'university_specialty_id' => 5,
            'created_by' => NULL,
            'updated_by' => NULL,
            'deleted_by' => NULL
        ]);

        \App\User::create([
            'first_name' => "يحيى",
            'second_name' => "محمد",
            'third_name' => "",
            'family_name' => "أبو شنب",
            'full_name' => 'يحيى محمد أبو شنب',
            'user_name' => "",
            'email' => 'yehya.m.shanab@gmail.com',
            'email_verified_at' => NULL,
            'password' => '$2y$10$Nhd6T9FBESYRVzhH47ridOCSRWMAJSsGWUiBFu3YeG1Xh1JP17wYG',
            'work_start_date' => '2019-09-01',
            'date_of_birth' => '1990-03-31',
            'id_number' => 802575746,
            'mobile' => NULL,
            'mobile_one' => 597828632,
            'mobile_two' => 598800949,
            'address' => NULL,
            'contract_type' => 'تجريبي',
            'remember_token' => NULL,
            'created_at' => '2019-09-25 10:43:43',
            'updated_at' => '2019-09-25 10:43:43',
            'deleted_at' => NULL,
            'neighborhood_id' => 101,
            
            'department_id' => 5,
            'social_status_id' => 8,
            'university_specialty_id' => 6,
            'created_by' => NULL,
            'updated_by' => NULL,
            'deleted_by' => NULL
        ]);

        \App\User::create([
            'first_name' => "فتحي",
            'second_name' => "صالح",
            'third_name' => "محمد",
            'family_name' => "أبو السبح",
            'full_name' => 'فتحي صالح محمد أبو السبح',
            'user_name' => "",
            'email' => NULL,
            'email_verified_at' => NULL,
            'password' => '$2y$10$mStNrVGuM5zOZ0UZkAEFOe.CeewQahGUAypaBIvbtJ1sCD.TrPMdq',
            'work_start_date' => '2010-02-01',
            'date_of_birth' => '2019-09-25',
            'id_number' => 942371733,
            'mobile' => NULL,
            'mobile_one' => 595843384,
            'mobile_two' => 599464407,
            'address' => 'شارع تونس قرب مدارس بنات الوكالة',
            'contract_type' => NULL,
            'remember_token' => NULL,
            'created_at' => '2019-09-25 10:43:43',
            'updated_at' => '2019-09-25 10:43:43',
            'deleted_at' => NULL,
            'neighborhood_id' => 178,
            'department_id' => 6,
            'social_status_id' => 8,
            'university_specialty_id' => 7,
            'created_by' => NULL,
            'updated_by' => NULL,
            'deleted_by' => NULL
        ]);

        \App\User::create([
            'first_name' => "أحمد",
            'second_name' => "زهير",
            'third_name' => "",
            'family_name' => "معروف",
            'full_name' => 'أحمد زهير معروف',
            'user_name' => "",
            'email' => NULL,
            'email_verified_at' => NULL,
            'password' => '$2y$10$5DPtnrlhewpyJFyhw53NIulfWYzX65NRPihWsFqGl8Q7LVamVXUfq',
            'work_start_date' => '2010-02-01',
            'date_of_birth' => '2019-09-25',
            'id_number' => 801019889,
            'mobile' => NULL,
            'mobile_one' => NULL,
            'mobile_two' => NULL,
            'address' => NULL,
            'contract_type' => NULL,
            'remember_token' => NULL,
            'created_at' => '2019-09-25 10:43:44',
            'updated_at' => '2019-09-25 10:43:44',
            'deleted_at' => NULL,
            'neighborhood_id' => NULL,
            
            'department_id' => 6,
            'social_status_id' => 8,
            'university_specialty_id' => 8,
            'created_by' => NULL,
            'updated_by' => NULL,
            'deleted_by' => NULL
        ]);

        \App\User::create([
            'first_name' => "رمضان",
            'second_name' => "خليل",
            'third_name' => "رمضان",
            'family_name' => "ارشي",
            'full_name' => 'رمضان خليل رمضان ارشي',
            'user_name' => "",
            'email' => NULL,
            'email_verified_at' => NULL,
            'password' => '$2y$10$kVEB3iE8mG4fJVF7scQWPu2uRahjLraer7uOs1Hm49L0HPk.4Sd8K',
            'work_start_date' => '2010-02-01',
            'date_of_birth' => '2019-09-25',
            'id_number' => 801329129,
            'mobile' => NULL,
            'mobile_one' => 599484927,
            'mobile_two' => NULL,
            'address' => 'شارع عبد الكريم العكلوك',
            'contract_type' => NULL,
            'remember_token' => NULL,
            'created_at' => '2019-09-25 10:43:44',
            'updated_at' => '2019-09-25 10:43:44',
            'deleted_at' => NULL,
            'neighborhood_id' => 178,
            'department_id' => 7,
            'social_status_id' => NULL,
            'university_specialty_id' => NULL,
            'created_by' => NULL,
            'updated_by' => NULL,
            'deleted_by' => NULL
        ]);

        \App\User::create([
            'first_name' => "حازم",
            'second_name' => "محمد",
            'third_name' => "نافع",
            'family_name' => "الفرا",
            'full_name' => 'حازم محمد نافع الفرا',
            'user_name' => "",
            'email' => NULL,
            'email_verified_at' => NULL,
            'password' => '$2y$10$hzsafaeUq3Qz0qWf4YFRuODiHC6f1Vm18jjPRRtcV5/mLb5CtFBzi',
            'work_start_date' => '2010-02-01',
            'date_of_birth' => '2019-09-25',
            'id_number' => 800088627,
            'mobile' => NULL,
            'mobile_one' => 599864330,
            'mobile_two' => NULL,
            'address' => NULL,
            'contract_type' => NULL,
            'remember_token' => NULL,
            'created_at' => '2019-09-25 10:43:44',
            'updated_at' => '2019-09-25 10:43:44',
            'deleted_at' => NULL,
            'neighborhood_id' => 252,
            
            'department_id' => 8,
            'social_status_id' => 8,
            'university_specialty_id' => 2,
            'created_by' => NULL,
            'updated_by' => NULL,
            'deleted_by' => NULL
        ]);

        \App\User::create([
            'first_name' => "فريد",
            'second_name' => "عمر",
            'third_name' => "عبد الهادي",
            'family_name' => "النواصرة",
            'full_name' => 'فريد عمر عبد الهادي النواصرة',
            'user_name' => "",
            'email' => 'Farid-omer@hotmail.com',
            'email_verified_at' => NULL,
            'password' => '$2y$10$GHOsZVE31qSoNIbUwIZKZ.DA22RM.ANw06pZTetXgfy2q7QYnvfqy',
            'work_start_date' => '2010-04-01',
            'date_of_birth' => '2019-09-25',
            'id_number' => 410172258,
            'mobile' => 2853951,
            'mobile_one' => 595915520,
            'mobile_two' => NULL,
            'address' => 'شارع النصر قرب بدري وهنية',
            'contract_type' => 'دائم',
            'remember_token' => NULL,
            'created_at' => '2019-09-25 10:43:44',
            'updated_at' => '2019-09-25 10:43:44',
            'deleted_at' => NULL,
            'neighborhood_id' => 252,
            
            'department_id' => 5,
            'social_status_id' => 8,
            'university_specialty_id' => 9,
            'created_by' => NULL,
            'updated_by' => NULL,
            'deleted_by' => NULL
        ]);

        \App\User::create([
            'first_name' => "رندة",
            'second_name' => "محمود",
            'third_name' => "خليل",
            'family_name' => "العكة",
            'full_name' => 'رندة محمود خليل العكة',
            'user_name' => "",
            'email' => NULL,
            'email_verified_at' => NULL,
            'password' => '$2y$10$GQz0J7sUhlZ6WUli9nrjP.wWlYn4KdqXCLRlKbs8G88KUAmWrNSfK',
            'work_start_date' => '2011-12-29',
            'date_of_birth' => '2019-09-25',
            'id_number' => 800580771,
            'mobile' => NULL,
            'mobile_one' => NULL,
            'mobile_two' => NULL,
            'address' => NULL,
            'contract_type' => NULL,
            'remember_token' => NULL,
            'created_at' => '2019-09-25 10:43:44',
            'updated_at' => '2019-09-25 10:43:44',
            'deleted_at' => NULL,
            'neighborhood_id' => 108,
            
            'department_id' => 9,
            'social_status_id' => NULL,
            'university_specialty_id' => 6,
            'created_by' => NULL,
            'updated_by' => NULL,
            'deleted_by' => NULL
        ]);

        \App\User::create([
            'first_name' => "سمر",
            'second_name' => "محمد",
            'third_name' => "خليل",
            'family_name' => "المصري",
            'full_name' => 'سمر محمد خليل المصري',
            'user_name' => "",
            'email' => 'tech@yardimeli.org.ps',
            'email_verified_at' => NULL,
            'password' => '$2y$10$fYAaBZoadOrha3voDyVB..Fs274P31wDO4wTRkOVvpLxznJkVxvum',
            'work_start_date' => '2012-02-01',
            'date_of_birth' => '2019-09-25',
            'id_number' => 900636416,
            'mobile' => NULL,
            'mobile_one' => 592434927,
            'mobile_two' => NULL,
            'address' => 'شارع حمزة بن عبد المطلب قرب سوق اليرموك',
            'contract_type' => 'دائم',
            'remember_token' => NULL,
            'created_at' => '2019-09-25 10:43:44',
            'updated_at' => '2019-09-25 10:43:44',
            'deleted_at' => NULL,
            'neighborhood_id' => 88,
            
            'department_id' => 6,
            'social_status_id' => 8,
            'university_specialty_id' => 8,
            'created_by' => NULL,
            'updated_by' => NULL,
            'deleted_by' => NULL
        ]);

        \App\User::create([
            'first_name' => "أشرف",
            'second_name' => "محمد",
            'third_name' => "أحمد",
            'family_name' => "عقل",
            'full_name' => 'أشرف محمد أحمد عقل',
            'user_name' => "",
            'email' => NULL,
            'email_verified_at' => NULL,
            'password' => '$2y$10$ayEvbHRBQAowd7KWBNGHeOKnv8qMM64OTG09b4ztIwzOtPdVttJyy',
            'work_start_date' => '2012-05-20',
            'date_of_birth' => '2019-09-25',
            'id_number' => 801759473,
            'mobile' => NULL,
            'mobile_one' => NULL,
            'mobile_two' => NULL,
            'address' => NULL,
            'contract_type' => NULL,
            'remember_token' => NULL,
            'created_at' => '2019-09-25 10:43:44',
            'updated_at' => '2019-09-25 10:43:44',
            'deleted_at' => NULL,
            'neighborhood_id' => NULL,
            
            'department_id' => 10,
            'social_status_id' => 8,
            'university_specialty_id' => 7,
            'created_by' => NULL,
            'updated_by' => NULL,
            'deleted_by' => NULL
        ]);

        \App\User::create([
            'first_name' => "محمد",
            'second_name' => "محمد",
            'third_name' => "خليل",
            'family_name' => "الرملاوي",
            'full_name' => 'محمد محمد خليل الرملاوي',
            'user_name' => "",
            'email' => NULL,
            'email_verified_at' => NULL,
            'password' => '$2y$10$MiDYKgMZCyUVhY1/2qqfqeQDnanrmRMuukPqzbxhI4PLWPCgr/Pue',
            'work_start_date' => '2012-08-14',
            'date_of_birth' => '2019-09-25',
            'id_number' => 901537962,
            'mobile' => NULL,
            'mobile_one' => NULL,
            'mobile_two' => NULL,
            'address' => NULL,
            'contract_type' => NULL,
            'remember_token' => NULL,
            'created_at' => '2019-09-25 10:43:44',
            'updated_at' => '2019-09-25 10:43:44',
            'deleted_at' => NULL,
            'neighborhood_id' => NULL,
            
            'department_id' => 8,
            'social_status_id' => 8,
            'university_specialty_id' => 7,
            'created_by' => NULL,
            'updated_by' => NULL,
            'deleted_by' => NULL
        ]);

        \App\User::create([
            'first_name' => "عبد الله",
            'second_name' => "عبد الكريم",
            'third_name' => "هاشم",
            'family_name' => "يونس",
            'full_name' => 'عبد الله عبد الكريم هاشم يونس',
            'user_name' => "",
            'email' => NULL,
            'email_verified_at' => NULL,
            'password' => '$2y$10$RRc.kl6/TdqxtPP/x/cVt.MMdzoAuWk1dTM1vktkjtiC8RGmMexUC',
            'work_start_date' => '2012-12-15',
            'date_of_birth' => '2019-09-25',
            'id_number' => 411760044,
            'mobile' => 2843997,
            'mobile_one' => 595429113,
            'mobile_two' => NULL,
            'address' => 'قرب برج الشفاء',
            'contract_type' => NULL,
            'remember_token' => NULL,
            'created_at' => '2019-09-25 10:43:44',
            'updated_at' => '2019-09-25 10:43:44',
            'deleted_at' => NULL,
            'neighborhood_id' => 252,
            
            'department_id' => 8,
            'social_status_id' => 8,
            'university_specialty_id' => 7,
            'created_by' => NULL,
            'updated_by' => NULL,
            'deleted_by' => NULL
        ]);

        \App\User::create([
            'first_name' => "نسمة",
            'second_name' => "رفيق",
            'third_name' => "يوسف",
            'family_name' => "قزعاط",
            'full_name' => 'نسمة  رفيق يوسف قزعاط',
            'user_name' => "",
            'email' => 'nesma980@',
            'email_verified_at' => NULL,
            'password' => '$2y$10$4SlkncYo5iMYtl.Cben.QeJWqgC2UpBO5fBrSgQZk1/B/mVZQGvkO',
            'work_start_date' => '2013-05-15',
            'date_of_birth' => '2019-09-25',
            'id_number' => 800501991,
            'mobile' => NULL,
            'mobile_one' => 595580101,
            'mobile_two' => 599620782,
            'address' => 'شارع بلال بن رباح قرب مسجد بلال',
            'contract_type' => 'دائم',
            'remember_token' => NULL,
            'created_at' => '2019-09-25 10:43:44',
            'updated_at' => '2019-09-25 10:43:44',
            'deleted_at' => NULL,
            'neighborhood_id' => 92,
            
            'department_id' => 4,
            'social_status_id' => 8,
            'university_specialty_id' => 5,
            'created_by' => NULL,
            'updated_by' => NULL,
            'deleted_by' => NULL
        ]);

        \App\User::create([
            'first_name' => "عطا",
            'second_name' => "عبد الرحمن",
            'third_name' => "",
            'family_name' => "أبو عطا",
            'full_name' => 'عطا عبد الرحمن أبو عطا',
            'user_name' => "",
            'email' => NULL,
            'email_verified_at' => NULL,
            'password' => '$2y$10$vkYhrW8ei0OFB0psDnEK4eylLFxvwXaN4p8bsYsFXbFdPRyeNFqdS',
            'work_start_date' => '2013-05-25',
            'date_of_birth' => '2019-09-25',
            'id_number' => 801579889,
            'mobile' => NULL,
            'mobile_one' => 599630704,
            'mobile_two' => NULL,
            'address' => 'بالقرب من السوق',
            'contract_type' => NULL,
            'remember_token' => NULL,
            'created_at' => '2019-09-25 10:43:44',
            'updated_at' => '2019-09-25 10:43:44',
            'deleted_at' => NULL,
            'neighborhood_id' => 282,
            
            'department_id' => 4,
            'social_status_id' => 8,
            'university_specialty_id' => 7,
            'created_by' => NULL,
            'updated_by' => NULL,
            'deleted_by' => NULL
        ]);

        \App\User::create([
            'first_name' => "روضة",
            'second_name' => "ناهض",
            'third_name' => "عبد الرحمن",
            'family_name' => "حلس",
            'full_name' => 'روضة ناهض عبد الرحمن حلس',
            'user_name' => "",
            'email' => NULL,
            'email_verified_at' => NULL,
            'password' => '$2y$10$8p7MPG2CfVubfUU.YdgeluY4EWanAZ3GrcxWdLn/JOz5Ev/aGPbqm',
            'work_start_date' => '2013-05-25',
            'date_of_birth' => '2019-09-25',
            'id_number' => 800803199,
            'mobile' => NULL,
            'mobile_one' => 598717146,
            'mobile_two' => NULL,
            'address' => NULL,
            'contract_type' => NULL,
            'remember_token' => NULL,
            'created_at' => '2019-09-25 10:43:44',
            'updated_at' => '2019-09-25 10:43:44',
            'deleted_at' => NULL,
            'neighborhood_id' => 67,
            
            'department_id' => 4,
            'social_status_id' => 5,
            'university_specialty_id' => NULL,
            'created_by' => NULL,
            'updated_by' => NULL,
            'deleted_by' => NULL
        ]);

        \App\User::create([
            'first_name' => "ميسون",
            'second_name' => "محمد",
            'third_name' => "أحمد",
            'family_name' => "الغمري",
            'full_name' => 'ميسون محمد أحمد الغمري',
            'user_name' => "",
            'email' => NULL,
            'email_verified_at' => NULL,
            'password' => '$2y$10$bXpMk4NPtfrvW5ZggMLdb.r7U3hTW7G5HzaJZKS5d6kVxdzCFoUYe',
            'work_start_date' => '2013-06-01',
            'date_of_birth' => '2019-09-25',
            'id_number' => 802229757,
            'mobile' => NULL,
            'mobile_one' => NULL,
            'mobile_two' => NULL,
            'address' => NULL,
            'contract_type' => NULL,
            'remember_token' => NULL,
            'created_at' => '2019-09-25 10:43:44',
            'updated_at' => '2019-09-25 10:43:44',
            'deleted_at' => NULL,
            'neighborhood_id' => NULL,
            'department_id' => 11,
            'social_status_id' => 8,
            'university_specialty_id' => 7,
            'created_by' => NULL,
            'updated_by' => NULL,
            'deleted_by' => NULL
        ]);

        \App\User::create([
            'first_name' => "وصال",
            'second_name' => "محمد",
            'third_name' => "أحمد",
            'family_name' => "الغمري",
            'full_name' => 'وصال  محمد أحمد الغمري',
            'user_name' => "",
            'email' => NULL,
            'email_verified_at' => NULL,
            'password' => '$2y$10$RK.IsRCiBheazOrPeilpKO/xkaMYe8WHtOJeQYrnM1Mk/nOjwa2N.',
            'work_start_date' => '2013-06-01',
            'date_of_birth' => '2019-09-25',
            'id_number' => 803611052,
            'mobile' => NULL,
            'mobile_one' => NULL,
            'mobile_two' => NULL,
            'address' => NULL,
            'contract_type' => NULL,
            'remember_token' => NULL,
            'created_at' => '2019-09-25 10:43:44',
            'updated_at' => '2019-09-25 10:43:44',
            'deleted_at' => NULL,
            'neighborhood_id' => NULL,
            'department_id' => 11,
            'social_status_id' => 8,
            'university_specialty_id' => 7,
            'created_by' => NULL,
            'updated_by' => NULL,
            'deleted_by' => NULL
        ]);

        \App\User::create([
            'first_name' => "عبد المعطي",
            'second_name' => "راتب",
            'third_name' => "عبد المعطي",
            'family_name' => "البابا",
            'full_name' => 'عبد المعطي راتب عبد المعطي البابا',
            'user_name' => "",
            'email' => 'eng-abdelmoty@hotmail.com',
            'email_verified_at' => NULL,
            'password' => '$2y$10$X7zwhojEC99..nyh9Zhxn.WpyWSxfKAxoBXL2lEAghqNfwT/0FvYe',
            'work_start_date' => '2013-06-25',
            'date_of_birth' => '2019-09-25',
            'id_number' => 800336802,
            'mobile' => 2626247,
            'mobile_one' => 599831610,
            'mobile_two' => NULL,
            'address' => 'شارع جامعة الدول العربية قرب مستشفى القدس',
            'contract_type' => 'دائم',
            'remember_token' => NULL,
            'created_at' => '2019-09-25 10:43:45',
            'updated_at' => '2019-09-25 10:43:45',
            'deleted_at' => NULL,
            'neighborhood_id' => 108,
            
            'department_id' => 8,
            'social_status_id' => 8,
            'university_specialty_id' => 2,
            'created_by' => NULL,
            'updated_by' => NULL,
            'deleted_by' => NULL
        ]);

        \App\User::create([
            'first_name' => "هالة",
            'second_name' => "حسن",
            'third_name' => "محمد",
            'family_name' => "عبدو",
            'full_name' => 'هالة حسن محمد عبدو',
            'user_name' => "",
            'email' => NULL,
            'email_verified_at' => NULL,
            'password' => '$2y$10$fzKFpdLzW7LgOaxfhKhQou.qKzJgSqSj884H63UXoLwrFR3m8Q42C',
            'work_start_date' => '2013-07-20',
            'date_of_birth' => '2019-09-25',
            'id_number' => 949826291,
            'mobile' => NULL,
            'mobile_one' => 599053674,
            'mobile_two' => NULL,
            'address' => NULL,
            'contract_type' => NULL,
            'remember_token' => NULL,
            'created_at' => '2019-09-25 10:43:45',
            'updated_at' => '2019-09-25 10:43:45',
            'deleted_at' => NULL,
            'neighborhood_id' => 87,
            
            'department_id' => 9,
            'social_status_id' => 3,
            'university_specialty_id' => 7,
            'created_by' => NULL,
            'updated_by' => NULL,
            'deleted_by' => NULL
        ]);

        \App\User::create([
            'first_name' => "أحمد",
            'second_name' => "جمعة",
            'third_name' => "لطفي",
            'family_name' => "أبو عساكر",
            'full_name' => 'أحمد جمعة لطفي أبو عساكر',
            'user_name' => "",
            'email' => NULL,
            'email_verified_at' => NULL,
            'password' => '$2y$10$uMgDneg6u1i0WpjB.bIDq.ulgdHN5Vnpc4oIohKE/gTDAUnffHXXO',
            'work_start_date' => '2013-09-15',
            'date_of_birth' => '2019-09-25',
            'id_number' => 926731076,
            'mobile' => NULL,
            'mobile_one' => 592229881,
            'mobile_two' => NULL,
            'address' => NULL,
            'contract_type' => NULL,
            'remember_token' => NULL,
            'created_at' => '2019-09-25 10:43:45',
            'updated_at' => '2019-09-25 10:43:45',
            'deleted_at' => NULL,
            'neighborhood_id' => NULL,
            'department_id' => 3,
            'social_status_id' => 8,
            'university_specialty_id' => 7,
            'created_by' => NULL,
            'updated_by' => NULL,
            'deleted_by' => NULL
        ]);

        \App\User::create([
            'first_name' => "أسامة",
            'second_name' => "شحادة",
            'third_name' => "",
            'family_name' => "البريم",
            'full_name' => 'أسامة شحادة البريم',
            'user_name' => "",
            'email' => NULL,
            'email_verified_at' => NULL,
            'password' => '$2y$10$.8HK8KMnBUP9oW7Xbt8hV.N.J.aYClDaxFymN5QmQ8MQ0em0IK9oK',
            'work_start_date' => '2013-10-02',
            'date_of_birth' => '2019-09-25',
            'id_number' => 801710179,
            'mobile' => NULL,
            'mobile_one' => NULL,
            'mobile_two' => NULL,
            'address' => NULL,
            'contract_type' => NULL,
            'remember_token' => NULL,
            'created_at' => '2019-09-25 10:43:45',
            'updated_at' => '2019-09-25 10:43:45',
            'deleted_at' => NULL,
            'neighborhood_id' => 218,
            'department_id' => 4,
            'social_status_id' => 5,
            'university_specialty_id' => 7,
            'created_by' => NULL,
            'updated_by' => NULL,
            'deleted_by' => NULL
        ]);

        \App\User::create([
            'first_name' => "محمد",
            'second_name' => "حسين",
            'third_name' => "موسى",
            'family_name' => "أبو دراز",
            'full_name' => 'محمد حسين موسى أبو دراز',
            'user_name' => "",
            'email' => NULL,
            'email_verified_at' => NULL,
            'password' => '$2y$10$/J.HF6ZhGgZQpjzDI7XHtumeCumB1RoAZfIdv439gPuAGsUeKutvS',
            'work_start_date' => '2013-11-06',
            'date_of_birth' => '2019-09-25',
            'id_number' => 903077196,
            'mobile' => NULL,
            'mobile_one' => 592593259,
            'mobile_two' => NULL,
            'address' => NULL,
            'contract_type' => NULL,
            'remember_token' => NULL,
            'created_at' => '2019-09-25 10:43:45',
            'updated_at' => '2019-09-25 10:43:45',
            'deleted_at' => NULL,
            'neighborhood_id' => 210,
            'department_id' => 4,
            'social_status_id' => 8,
            'university_specialty_id' => NULL,
            'created_by' => NULL,
            'updated_by' => NULL,
            'deleted_by' => NULL
        ]);

        \App\User::create([
            'first_name' => "حماد",
            'second_name' => "حامد",
            'third_name' => "مصطفى",
            'family_name' => "عوكل",
            'full_name' => 'حماد حامد مصطفى عوكل',
            'user_name' => "",
            'email' => NULL,
            'email_verified_at' => NULL,
            'password' => '$2y$10$A8hawtU3O9EtVOq/g9RMw.bThFKplW2gr/TMUgaumV1l.mrJkWtaq',
            'work_start_date' => '2013-11-06',
            'date_of_birth' => '2019-09-25',
            'id_number' => 800341570,
            'mobile' => NULL,
            'mobile_one' => 599865143,
            'mobile_two' => NULL,
            'address' => 'شارع طه حسين',
            'contract_type' => NULL,
            'remember_token' => NULL,
            'created_at' => '2019-09-25 10:43:45',
            'updated_at' => '2019-09-25 10:43:45',
            'deleted_at' => NULL,
            'neighborhood_id' => 287,
            
            'department_id' => 4,
            'social_status_id' => 8,
            'university_specialty_id' => NULL,
            'created_by' => NULL,
            'updated_by' => NULL,
            'deleted_by' => NULL
        ]);

        \App\User::create([
            'first_name' => "هبة",
            'second_name' => "محمود",
            'third_name' => "محمد",
            'family_name' => "رجب",
            'full_name' => 'هبة محمود محمد رجب',
            'user_name' => "",
            'email' => NULL,
            'email_verified_at' => NULL,
            'password' => '$2y$10$HT9gJqZaiL/gUTN7qFPlAu9ljbyE1V5WxnC01aW7eppcXV68KN.KC',
            'work_start_date' => '2014-04-14',
            'date_of_birth' => '2019-09-25',
            'id_number' => 800545287,
            'mobile' => NULL,
            'mobile_one' => NULL,
            'mobile_two' => NULL,
            'address' => NULL,
            'contract_type' => NULL,
            'remember_token' => NULL,
            'created_at' => '2019-09-25 10:43:45',
            'updated_at' => '2019-09-25 10:43:45',
            'deleted_at' => NULL,
            'neighborhood_id' => NULL,
            
            'department_id' => 4,
            'social_status_id' => 8,
            'university_specialty_id' => 7,
            'created_by' => NULL,
            'updated_by' => NULL,
            'deleted_by' => NULL
        ]);

        \App\User::create([
            'first_name' => "تامر",
            'second_name' => "صالح",
            'third_name' => "محمود",
            'family_name' => "البشيتي",
            'full_name' => 'تامر صالح محمود البشيتي',
            'user_name' => "",
            'email' => NULL,
            'email_verified_at' => NULL,
            'password' => '$2y$10$hOi..JbiuRXfbS6sPnlFzusJko4GrxweMZo6cph/WK0IH2ULEfKPO',
            'work_start_date' => '2014-09-23',
            'date_of_birth' => '2019-09-25',
            'id_number' => 905511762,
            'mobile' => NULL,
            'mobile_one' => 599164585,
            'mobile_two' => NULL,
            'address' => NULL,
            'contract_type' => NULL,
            'remember_token' => NULL,
            'created_at' => '2019-09-25 10:43:45',
            'updated_at' => '2019-09-25 10:43:45',
            'deleted_at' => NULL,
            'neighborhood_id' => 267,
            
            'department_id' => 4,
            'social_status_id' => 8,
            'university_specialty_id' => 7,
            'created_by' => NULL,
            'updated_by' => NULL,
            'deleted_by' => NULL
        ]);

        \App\User::create([
            'first_name' => "إسراء",
            'second_name' => "خالد",
            'third_name' => "عبد العزيز",
            'family_name' => "حجازي",
            'full_name' => 'إسراء خالد عبد العزيز حجازي',
            'user_name' => "",
            'email' => NULL,
            'email_verified_at' => NULL,
            'password' => '$2y$10$t1pz6wvx3LMXIMK1yhmfWe7bxmfHGppIHoiF/Ak/ZjCNiNw99K6Xu',
            'work_start_date' => '2014-12-16',
            'date_of_birth' => '2019-09-25',
            'id_number' => 400739991,
            'mobile' => NULL,
            'mobile_one' => 599083908,
            'mobile_two' => 597116445,
            'address' => 'شارع المخابرات برج 6',
            'contract_type' => NULL,
            'remember_token' => NULL,
            'created_at' => '2019-09-25 10:43:45',
            'updated_at' => '2019-09-25 10:43:45',
            'deleted_at' => NULL,
            'neighborhood_id' => 286,
            
            'department_id' => 12,
            'social_status_id' => 8,
            'university_specialty_id' => 8,
            'created_by' => NULL,
            'updated_by' => NULL,
            'deleted_by' => NULL
        ]);

        \App\User::create([
            'first_name' => "محمد",
            'second_name' => "علاء",
            'third_name' => "حربي",
            'family_name' => "الفيومي",
            'full_name' => 'محمد علاء حربي الفيومي',
            'user_name' => "",
            'email' => 'mm9153105@gmail.com',
            'email_verified_at' => NULL,
            'password' => '$2y$10$lEYbVp/G3Sn7/c2sW.8QUOX3XwhhzgLQ9mZYt8/tRUlfpCNCFgqay',
            'work_start_date' => '2016-10-15',
            'date_of_birth' => '2019-09-25',
            'id_number' => 400880720,
            'mobile' => 2813411,
            'mobile_one' => 597213363,
            'mobile_two' => NULL,
            'address' => 'بالقرب من مسجد السيد علي المغربي',
            'contract_type' => 'تشغيل خريجين',
            'remember_token' => NULL,
            'created_at' => '2019-09-25 10:43:45',
            'updated_at' => '2019-09-25 10:43:45',
            'deleted_at' => NULL,
            'neighborhood_id' => 67,
            
            'department_id' => 13,
            'social_status_id' => 5,
            'university_specialty_id' => 11,
            'created_by' => NULL,
            'updated_by' => NULL,
            'deleted_by' => NULL
        ]);

        \App\User::create([
            'first_name' => "ماجد",
            'second_name' => "عبد الله",
            'third_name' => "محي الدين",
            'family_name' => "السرحي",
            'full_name' => 'ماجد عبد الله محي الدين السرحي',
            'user_name' => "",
            'email' => 'majeda.m.sarha@gmail.com',
            'email_verified_at' => NULL,
            'password' => '$2y$10$.6b1H.ErKXuUcg2ik4wopODnpzXnauzA.p3NQjjCN4WZqnBHIAOTa',
            'work_start_date' => '2016-10-15',
            'date_of_birth' => '2019-09-25',
            'id_number' => 400089959,
            'mobile' => NULL,
            'mobile_one' => 592125758,
            'mobile_two' => NULL,
            'address' => 'شارع صلاح الدين مقابل ديوان صيام',
            'contract_type' => 'تشغيل خريجين',
            'remember_token' => NULL,
            'created_at' => '2019-09-25 10:43:45',
            'updated_at' => '2019-09-25 10:43:45',
            'deleted_at' => NULL,
            'neighborhood_id' => 2,
            
            'department_id' => 13,
            'social_status_id' => 5,
            'university_specialty_id' => 12,
            'created_by' => NULL,
            'updated_by' => NULL,
            'deleted_by' => NULL
        ]);


        \App\User::create([
            'first_name' => "كفا",
            'second_name' => "",
            'third_name' => "",
            'family_name' => "ابو جبل",
            'full_name' => 'كفا ابو جبل',
        ]);

        \App\User::create([
            'first_name' => "فاطمه",
            'second_name' => "",
            'third_name' => "",
            'family_name' => "دياب",
            'full_name' => 'فاطمه دياب',
        ]);

        \App\User::create([
            'first_name' => "اسلام",
            'second_name' => "",
            'third_name' => "",
            'family_name' => "جابر",
            'full_name' => 'اسلام جابر',
        ]);
    }
}
